Python Libraries

Allows Mathematical Operations<br>
Faster operations

In [ ]:
import numpy as np

 List VS Numpy - time taken

In [ ]:
from time import process_time

In [21]:
# python_list = [i for i in range(10000000)]
# start_time=process_time()
# python_list=[i+1 for i in python_list]
# end_time = process_time()
# print(end_time-start_time)

In [22]:
# np_array = np.array([i for i in range(1000000)])
# start_time=process_time()
# np_array+=5
# end_time = process_time()
# # print(end_time-start_time)

Numpy Arrays

In [23]:
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [25]:
print('helllo')

helllo


In [26]:
b=np.array([(1,2,3,4,5,6),(7,8,9,10,11,12)])

In [28]:

print(b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [29]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)

In [30]:
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [31]:
#create numpy array of 0s
x=np.zeros((4,5))

In [32]:
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [33]:
#create numpy array of 1s
x=np.ones((4,5))

In [34]:
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [35]:
#array of particular value
z=np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [36]:
#create identity matrix
a=np.eye(4)

In [37]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
#create numpy array with random values
b=np.random.random((3,4))

In [41]:
b

array([[0.5097337 , 0.03535099, 0.54838477, 0.83235246],
       [0.61957953, 0.63799266, 0.4287767 , 0.08572496],
       [0.68222513, 0.04394548, 0.07904897, 0.17830068]])

In [42]:
#create numpy array with random values integers in  range
c=np.random.randint(10,100,(3,5))

In [43]:
c

array([[76, 24, 51, 75, 40],
       [87, 83, 48, 13, 11],
       [41, 18, 34, 19, 77]])

In [48]:
#array of evenly spaced values
d=np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [49]:
#array of evenly spaced vaues => speicifying the step
e=np.arange(10,30,5)
print(e)

[10 15 20 25]


In [50]:
#convert list to array
list1 = [10,20,30,40,50]
np_array=np.asarray(list1)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

Analyzing a numpy array


In [51]:
c=np.random.randint(10,90,(5,5))
print(c.shape)

(5, 5)


In [53]:
print(c.ndim)

2


In [56]:
print(c.size)

25


In [57]:
print(c.dtype)

int32


Mathematical operations

In [59]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
print(list1+list2)
#concat

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [61]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)
print(a+b)
#add

[[5 3 9]
 [2 0 5]
 [5 9 8]]
[[13 13 18]
 [11 11 13]
 [12 13 13]]
[[18 16 27]
 [13 11 18]
 [17 22 21]]


In [62]:
np.add(a,b)

array([[18, 16, 27],
       [13, 11, 18],
       [17, 22, 21]])

In [63]:
np.subtract(a,b)

array([[ -8, -10,  -9],
       [ -9, -11,  -8],
       [ -7,  -4,  -5]])

In [64]:
np.multiply(a,b)

array([[ 65,  39, 162],
       [ 22,   0,  65],
       [ 60, 117, 104]])

In [65]:
np.divide(a,b)

array([[0.38461538, 0.23076923, 0.5       ],
       [0.18181818, 0.        , 0.38461538],
       [0.41666667, 0.69230769, 0.61538462]])

Array Manipulation

In [67]:
array = np.random.randint(0,10,(2,3))
print(array)

[[2 8 9]
 [0 9 1]]


In [68]:
print(array.shape)

(2, 3)


In [69]:
#transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[2 0]
 [8 9]
 [9 1]]
(3, 2)


In [70]:
trans2 = array.T
trans2

array([[2, 0],
       [8, 9],
       [9, 1]])

In [71]:
print(trans2)
print(trans.shape)

[[2 0]
 [8 9]
 [9 1]]
(3, 2)


In [72]:
#reshaping a array
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[6 1 0]
 [0 3 9]]
(2, 3)


In [74]:
b=a.reshape(3,2)
print(b)
print(type(b))

[[6 1]
 [0 0]
 [3 9]]
<class 'numpy.ndarray'>
